In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
df = pd.read_csv("Advertising.csv")
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
from ydata_profiling import ProfileReport

In [4]:
tools = ProfileReport(df)
tools.to_widgets()


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
tools.to_file("Test.html")

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
# Feature (X)
x = df[["TV"]]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [8]:
# Labels (Y)
y = df["Sales"]
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [10]:
model.fit(x, y) # Finding the best value of m and c -> y = mx+c

LinearRegression()

In [11]:
model.intercept_ # intercept is c (or Error)

6.974821488229891

In [12]:
model.coef_ # coefficent is m

array([0.05546477])

`y = mx+c`

In [13]:
pickle.dump(model, open("Linear_Regression_Basic.pkl", "wb"))

In [14]:
model.predict([[45]])

E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [15]:
tv_sales = [4,5,6,7,89,34,45,67,23]

In [16]:
for i in tv_sales:
    print(model.predict([[i]]))

[7.19668057]
[7.25214534]
[7.30761011]
[7.36307488]
[11.91118606]
[8.86062368]
[9.47073616]
[10.69096111]
[8.25051121]


E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRe

In [17]:
saved_model = pickle.load(open("Linear_Regression_Basic.pkl", "rb"))

In [18]:
saved_model.predict([[45]])

E:\Tools_For_Study\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [19]:
saved_model.score(x, y)

0.8121757029987414

In [20]:
saved_model.score(x, y) # score -> it is R2 performance metrix

0.8121757029987414